PATH_OUTPUT = "records/"
PATH_INPUT = "currencies.json"
FORMAT_OUTPUT = "dca_%d_%m_%Y__%H_%M_%S"

COL_NAME = "name"
COL_SYMB = "symbol"
COL_WEIG = "weight"
COL_PRIC = "price ($FIAT)"
COL_VAR1 = "24h variation (%)"
COL_VAR2 = "variation tmp for computations"
COL_PUR1 = "purchase todo ($FIAT)"
COL_PUR2 = "purchase made ($FIAT)"
COL_AMO1 = "amount bought (token)"
COL_AMO2 = "amount obtained (token)"
